// Teste da API REST de agendamentos
@baseURL = http://localhost:3000/api/usuarios
@id = 684995b3ddb7c842ce44e0ca
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30


// ------------- GET ------------- //

###
// GET - Lista o usuário pelo ID
GET {{baseURL}}/{{id}}
Content-Type: application/json

###
// GET - Lista o usuário pelo ID (com erro)
GET {{baseURL}}/2
Content-Type: application/json

// ------------- POST ------------- //
###
// POST - Faz login do usuário
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "gueff@gmail.com",
    "password" : "math"
}

###
// POST - Faz login do usuário (senha errada)
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "gueff@gmail.com",
    "password" : "nada"
}

###
// POST - Faz login do usuário (email não cadastrado)
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "inexistente@gmail.com",
    "password" : "admin"
}

###
// POST - Faz login do usuário (com erro de validação)
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "gmail.com",
    "password" : ""
}

###
// POST - Insere um novo usuario Admin nivel 2 (Sem erros)
POST {{baseURL}}
Content-Type: application/json

{
    "name" : "Matheus A S Gueff",
    "email" : "gueff@gmail.com",
    "password" : "math",
    "nivel" : 2
}

###
// POST - Insere um novo usuario Admin nivel 1 (Sem erros)
POST {{baseURL}}
Content-Type: application/json

{
    "name" : "Davy Oliveira",
    "email" : "davy@gmail.com",
    "password" : "davy",
    "nivel" : 1
}

###
// POST - Insere um novo usuario Admin (Com erros)
POST {{baseURL}}
Content-Type: application/json

{
    "name" : "",
    "email" : "gueffmatheus@",
    "password" : "1",
    "nivel" : "sou admin"
}

// ------------- PUT ------------- //

###
// PUT - Edição de um usuário
PUT {{baseURL}}/{{id}}
Content-Type: application/json
access-token: {{token}}

{
    "name" : "Matheus Gueff",
    "email" : "gueff@gmail.com",
    "password" : "math",
    "newPassword" : "math"
}

###
// PUT - Edição de um usuário (Com erro de email existente e senha incorreta)
PUT {{baseURL}}/{{id}}
Content-Type: application/json
access-token: {{token}}

{
    "name" : "Matheus Gueff",
    "email" : "alice@gmail.com",
    "password" : "senhaErrada",
    "newPassword" : "math"
}

// ------------- DELETE ------------- //
###
// DELETE - Remove o usuario pelo id
DELETE {{baseURL}}/{{id}}
Content-Type: application/json
access-token: {{token}}

###
// DELETE - Remove o usuario pelo id (com erro)
DELETE {{baseURL}}/2
Content-Type: application/json
access-token: {{token}}