// Teste da API REST de agendamentos
@baseURL = http://localhost:3000/api/usuarios
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjg0ZjIwN2FkNGQwZTNlOTRkNDdmMjcxIiwibml2ZWwiOjJ9LCJpYXQiOjE3NTAwMTYxNTJ9.CKcdHV6AnOe1zyG8Pa6hn7HQUM13LK3L8m922P8kIgQ
@tokenToUpdate = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjg0ZjIwN2FkNGQwZTNlOTRkNDdmMjc1Iiwibml2ZWwiOjJ9LCJpYXQiOjE3NTAwMTYzNDl9.Re3uTkUeWlZz75agngNXikMqHrDI6FGmz7KUP5ZLjD8
@invalidToken = 23

@expiredToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjg0ZjIwN2FkNGQwZTNlOTRkNDdmMjcxIiwibml2ZWwiOjJ9LCJpYXQiOjE3NTAwMTYxODgsImV4cCI6MTc1MDAxNjE4OX0.tUYKr5P9VKMcB-i2wAGaY8LC-C-YFep-L3VCP0pHKXY

// ------------- GET ------------- //

###
// GET - Lista o usuário pelo ID decodificado do Token JWT
GET {{baseURL}}
Content-Type: application/json
access_token: {{token}}

###
// GET - Lista o usuário pelo ID decodificado do Token JWT(com erro de token expirado)
GET {{baseURL}}
Content-Type: application/json
access_token: {{expiredToken}}

###
// GET - Lista o usuário pelo ID decodificado do Token JWT(com erro de token inválido)
GET {{baseURL}}
Content-Type: application/json
access_token: {{invalidToken}}

###
// GET - Lista o usuário pelo ID decodificado do Token JWT (com erro)
GET {{baseURL}}
Content-Type: application/json

// ------------- POST ------------- //
###
// POST - Faz login do usuário
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "gueff@gmail.com",
    "password" : "Gueff12*"
}

###
// POST - Faz login do usuário (senha errada)
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "gueff@gmail.com",
    "password" : "nada"
}

###
// POST - Faz login do usuário (email não cadastrado)
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "inexistente@gmail.com",
    "password" : "admin"
}

###
// POST - Faz login do usuário (com erro de validação)
POST {{baseURL}}/login
Content-Type: application/json

{
    "email" : "gmail.com",
    "password" : ""
}

###
// POST - Insere um novo usuario Admin nivel 2 (Sem erros)
POST {{baseURL}}
Content-Type: application/json

{
    "name" : "Admin nivel 2",
    "email" : "admin2@gmail.com",
    "password" : "Senha12*",
    "nivel" : 1
}

###
// POST - Insere um novo usuario Admin nivel 1 (Sem erros)
POST {{baseURL}}
Content-Type: application/json

{
    "name" : "Davy Oliveira",
    "email" : "davy@gmail.com",
    "password" : "Davy12*",
    "nivel" : 1
}

###
// POST - Insere um novo usuario Admin nivel 1 (Com erros)
POST {{baseURL}}
Content-Type: application/json

{
    "name" : "",
    "email" : "gueffmatheus@",
    "password" : "1",
    "nivel" : "sou admin"
}

// ------------- PUT ------------- //

###
// PUT - Edição de um usuário adquirido pelo ID do token JWT enviado
PUT {{baseURL}}
Content-Type: application/json
access_token: {{tokenToUpdate}}

{
    "name" : "Matheus Gueff",
    "email" : "gueff@gmail.com",
    "password" : "Gueff12*",
    "newPassword" : "Math12*"
}

###
// PUT - Edição de um usuário (Com erro de email existente e senha incorreta)
PUT {{baseURL}}
Content-Type: application/json
access_token: {{token}}

{
    "name" : "Matheus Gueff",
    "email" : "alice@gmail.com",
    "password" : "senhaErrada",
    "newPassword" : "math"
}

// ------------- DELETE ------------- //
###
// DELETE - Remove o usuario pelo id adquirido do token JWT enviado
DELETE {{baseURL}}
Content-Type: application/json
access_token: {{tokenToUpdate}}

###
// DELETE - Remove o usuario pelo id adquirido do token JWT enviado (sem token passado)
DELETE {{baseURL}}
Content-Type: application/json